version: '3'
services:
  opal2:
    image: obiba/opal:latest
    ports:
      - "8845:8443"
      - "8881:8080"
    links:
      - rock2
      - mongo2
      - mysqldata2
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo2
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata2
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - ROCK_HOSTS=rock2:8085
    volumes:
      - ./opal2:/srv
  mongo2:
    image: mongo:4.2
  mysqldata2:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
  rock2:
    image: datashield/rock-base:latest
    volumes:
      - ./data2:/srv



